source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Heartland-iOS-SDK_Example' do
  pod "Heartland-iOS-SDK", :path => "../"
end

target 'Heartland-iOS-SDK_Tests' do
  pod "Heartland-iOS-SDK", :path => "../"

  
end
