# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Heartland-iOS-SDK_Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 
 use_frameworks!
pod "Heartland-iOS-SDK", :path => "../"

  # Pods for Heartland-iOS-SDK_Example
target 'Heartland-iOS-SDK_Tests' do
    
    inherit! :search_paths

end
end
