#import <Foundation/Foundation.h>
extern NSString * const UPA_MSG_ID_toString[];
extern NSString * const UPA_CARD_GROUP_toString[];
extern NSString * const UPA_MSG_TYPE_toString[];
extern NSString * const UPA_MSG_PROMPT_toString[];

typedef NS_ENUM(NSInteger, UPA_MSG_ID) {
    UPA_MSG_ID_LANE_OPEN,
    UPA_MSG_ID_LANE_CLOSE,
    UPA_MSG_ID_RESET,
    UPA_MSG_ID_REBOOT,
    UPA_MSG_ID_BATCH_CLOSE,
    UPA_MSG_ID_GET_BATCH_REPORT,
    UPA_MSG_ID_SALE,
    UPA_MSG_ID_REFUND,
    UPA_MSG_ID_VOID,
    UPA_MSG_ID_CARD_VERIFY,
    UPA_MSG_ID_AUTH,
    UPA_MSG_ID_BALANCE,
    UPA_MSG_ID_ADD_VALUE,
    UPA_MSG_ID_TIP_ADJUST,
    UPA_MSG_ID_GET_INFO_REPORT,
    UPA_MSG_ID_CAPTURE,
    UPA_MSG_ID_SEND_SAF,
    UPA_MSG_ID_GET_DIAGNOSTIC_REPORT,
    UPA_MSG_ID_EXECUTE_EOD,
    UPA_MSG_ID_REVERSAL,
    UPA_MSG_ID_LINE_ITEM_DISPLAY,
    UPA_MSG_ID_DELETE_PREAUTH,
    UPA_MSG_ID_GET_SIGNATURE,
};

typedef NS_ENUM(NSInteger, UPA_CARD_GROUP) {
    UPA_CARD_GROUP_CREDIT,
    UPA_CARD_GROUP_DEBIT,
    UPA_CARD_GROUP_GIFT,
    UPA_CARD_GROUP_EBT,
    UPA_CARD_GROUP_ALL
};

typedef NS_ENUM(NSInteger, UPA_MSG_TYPE) {
    UPA_MSG_TYPE_UNKNOWN,
    UPA_MSG_TYPE_ACK,
    UPA_MSG_TYPE_NAK,
    UPA_MSG_TYPE_READY,
    UPA_MSG_TYPE_BUSY,
    UPA_MSG_TYPE_TIMEOUT,
    UPA_MSG_TYPE_MSG,
    UPA_MSG_TYPE_DATA,
    UPA_MSG_TYPE_PROMPT1,
    UPA_MSG_TYPE_BC,
};

typedef NS_ENUM(NSInteger, UPA_TRANSACTION_COUNTRY_TYPE) {
    UPA_TRANSACTION_TYPE_CANADA,
    UPA_TRANSACTION_TYPE_USA
};


@interface UpaEnums : NSObject

@end
